### ISSUE TITLE
Bug : Negative count of tabs on Firefox 64 bits on Windows

### ISSUE THREAD

**Issue by sebma** [BenjiWiebe/tab-count#2]
Hi,

I installed Firefox 64 bits from [Firefox 64 bits releases](https://www.mozilla.org/en-US/firefox/all/?q=english) on Widows 8

Your addon sometimes shows a negative count of tabs.

Can you have a look ?

**Comment by BenjiWiebe** [comment]
@sebma Yes this is a known bug. For now, click the number to force a recount. I'm not sure what the correct way to fix this is.

**Comment by BenjiWiebe** [comment]
I haven't seen this bug anymore for a long time. Perhaps the API has changed? If someone can reproduce it, please let me know.
